# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rails db:seed command (or created alongside the database with db:setup).
#
# Examples:
#
#   movies = Movie.create([{ name: 'Star Wars' }, { name: 'Lord of the Rings' }])
#   Character.create(name: 'Luke', movie: movies.first)
# Bowl.create(teams: Team.create([{name: 'Kentucky', team_record: '7-5'}, {name: 'Georgia Tech', team_record: '8-4'}]), bowl: Bowl.create(name:'TaxSlayer', points: 10, game_date: '2016-12-31'))

Bowl.create(name:'New Mexico', points: 12, game_date: '2016-12-17', teams: Team.create([{name: 'UTSA', team_record: '6-6'}, {name: 'New Mexico', team_record: '8-4'}]))
Bowl.create(name:'Las Vegas', points: 24, game_date: '2016-12-17', teams: Team.create([{name: 'Houston', team_record: '9-3'}, {name: 'San Diego State', team_record: '10-3'}]))
Bowl.create(name:'Camellia', points: 12, game_date: '2016-12-17', teams: Team.create([{name: 'Appalachian State', team_record: '9-3'}, {name: 'Toledo', team_record: '9-3'}]))
Bowl.create(name:'Cure', points: 12, game_date: '2016-12-17', teams: Team.create([{name: 'UCF', team_record: '9-3'}, {name: 'Arkansas State', team_record: '7-5'}]))
Bowl.create(name:'New Orleans', points: 12, game_date: '2016-12-17', teams: Team.create([{name: 'Southern Miss', team_record: '6-6'}, {name: 'Louisiana Lafayette', team_record: '6-6'}]))
Bowl.create(name:'Miami Beach', points: 12, game_date: '2016-12-19', teams: Team.create([{name: 'Central Michigan', team_record: '6-6'}, {name: 'Tulsa', team_record: '9-3'}]))
Bowl.create(name:'Boca Raton', points: 12, game_date: '2016-12-20', teams: Team.create([{name: 'WKU', team_record: '10-3'}, {name: 'Memphis', team_record: '8-4'}]))
Bowl.create(name:'Poinsettia', points: 12, game_date: '2016-12-21', teams: Team.create([{name: 'BYU', team_record: '8-4'}, {name: 'Wyoming', team_record: '8-5'}]))
Bowl.create(name:'Idaho Potato', points: 12, game_date: '2016-12-22', teams: Team.create([{name: 'Idaho', team_record: '8-4'}, {name: 'Colorado State', team_record: '7-5'}]))
Bowl.create(name:'Bahamas', points: 12, game_date: '2016-12-23', teams: Team.create([{name: 'Eastern Michigan', team_record: '7-5'}, {name: 'Old Dominion', team_record: '9-3'}]))
Bowl.create(name:'Armed Forces', points: 12, game_date: '2016-12-23', teams: Team.create([{name: 'Navy', team_record: '8-4'}, {name: 'Louisiana Tech', team_record: '8-4'}]))
Bowl.create(name:'Dollar General', points: 12, game_date: '2016-12-23', teams: Team.create([{name: 'Troy', team_record: '9-3'}, {name: 'Ohio', team_record: '8-5'}]))
Bowl.create(name:'Hawaii', points: 12, game_date: '2016-12-24', teams: Team.create([{name: 'Hawaii', team_record: '6-7'}, {name: 'Middle Tennessee', team_record: '8-4'}]))
Bowl.create(name:'St. Petersburg', points: 12, game_date: '2016-12-26', teams: Team.create([{name: 'Mississippi State', team_record: '5-7'}, {name: 'Miami (Ohio)', team_record: '6-6'}]))
Bowl.create(name:'Quick Lane', points: 12, game_date: '2016-12-26', teams: Team.create([{name: 'Maryland', team_record: '6-6'}, {name: 'Boston College', team_record: '6-6'}]))
Bowl.create(name:'Independence', points: 12, game_date: '2016-12-26', teams: Team.create([{name: 'NC State', team_record: '6-6'}, {name: 'Vanderbilt', team_record: '6-6'}]))
Bowl.create(name:'Heart of Dallas', points: 12, game_date: '2016-12-27', teams: Team.create([{name: 'Army', team_record: '6-5'}, {name: 'North Texas', team_record: '5-7'}]))
Bowl.create(name:'Military', points: 12, game_date: '2016-12-27', teams: Team.create([{name: 'Temple', team_record: '10-3'}, {name: 'Wake Forest', team_record: '6-6'}]))
Bowl.create(name:'Holiday', points: 24, game_date: '2016-12-27', teams: Team.create([{name: 'Minnesota', team_record: '8-4'}, {name: 'Washington State', team_record: '8-4'}]))
Bowl.create(name:'Cactus', points: 24, game_date: '2016-12-27', teams: Team.create([{name: 'Baylor', team_record: '6-6'}, {name: 'Boise State', team_record: '10-2'}]))
Bowl.create(name:'Pinstripe', points: 24, game_date: '2016-12-28', teams: Team.create([{name: 'Pittsburgh', team_record: '8-4'}, {name: 'Northwestern', team_record: '6-6'}]))
Bowl.create(name:'Russell Athletic', points: 24, game_date: '2016-12-28', teams: Team.create([{name: 'Miami', team_record: '8-4'}, {name: 'West Virginia', team_record: '10-2'}]))
Bowl.create(name:'Foster Farms', points: 12, game_date: '2016-12-28', teams: Team.create([{name: 'Indiana', team_record: '6-6'}, {name: 'Utah', team_record: '8-4'}]))
Bowl.create(name:'Texas', points: 24, game_date: '2016-12-28', teams: Team.create([{name: 'Texas A&M', team_record: '8-4'}, {name: 'Kansas State', team_record: '8-4'}]))
Bowl.create(name:'Birmingham', points: 12, game_date: '2016-12-29', teams: Team.create([{name: 'South Carolina', team_record: '6-6'}, {name: 'South Florida', team_record: '10-2'}]))
Bowl.create(name:'Belk', points: 24, game_date: '2016-12-29', teams: Team.create([{name: 'Arkansas', team_record: '7-5'}, {name: 'Virginia Tech', team_record: '9-4'}]))
Bowl.create(name:'Alamo', points: 24, game_date: '2016-12-29', teams: Team.create([{name: 'Oklahoma State', team_record: '9-3'}, {name: 'Colorado', team_record: '10-3'}]))
Bowl.create(name:'Liberty', points: 24, game_date: '2016-12-30', teams: Team.create([{name: 'Georgia', team_record: '7-5'}, {name: 'TCU', team_record: '6-6'}]))
Bowl.create(name:'Sun', points: 24, game_date: '2016-12-30', teams: Team.create([{name: 'Stanford', team_record: '9-3'}, {name: 'North Carolina', team_record: '8-4'}]))
Bowl.create(name:'Music City', points: 24, game_date: '2016-12-30', teams: Team.create([{name: 'Nebraksa', team_record: '9-3'}, {name: 'Tennessee', team_record: '8-4'}]))
Bowl.create(name:'Arizona', points: 12, game_date: '2016-12-30', teams: Team.create([{name: 'Air Force', team_record: '9-3'}, {name: 'South Alabama', team_record: '6-6'}]))
Bowl.create(name:'Citrus', points: 24, game_date: '2016-12-31', teams: Team.create([{name: 'Louisville', team_record: '9-3'}, {name: 'LSU', team_record: '7-4'}]))
Bowl.create(name:'TaxSlayer', points: 24, game_date: '2016-12-31', teams: Team.create([{name: 'Georgia Tech', team_record: '8-4'}, {name: 'Kentucky', team_record: '7-5'}]))
Bowl.create(name:'Outback', points: 24, game_date: '2017-1-2', teams: Team.create([{name: 'Florida', team_record: '8-4'}, {name: 'Iowa', team_record: '8-4'}]))
Bowl.create(name:'Orange', points: 36, game_date: '2016-12-30', teams: Team.create([{name: 'Florida State', team_record: '9-3'}, {name: 'Michigan', team_record: '10-2'}]))
Bowl.create(name:'Peach', points: 36, game_date: '2016-12-31', teams: Team.create([{name: 'Alabama', team_record: '13-0'}, {name: 'Washington', team_record: '12-1'}]))
Bowl.create(name:'Fiesta', points: 36, game_date: '2016-12-31', teams: Team.create([{name: 'Clemson', team_record: '12-1'}, {name: 'Ohio State', team_record: '11-1'}]))
Bowl.create(name:'Cotton', points: 36, game_date: '2017-1-2', teams: Team.create([{name: 'Western Michigan', team_record: '13-0'}, {name: 'Wisconsin', team_record: '10-3'}]))
Bowl.create(name:'Rose', points: 36, game_date: '2017-1-2', teams: Team.create([{name: 'Penn State', team_record: '11-2'}, {name: 'USC', team_record: '9-3'}]))
Bowl.create(name:'Sugar', points: 36, game_date: '2017-1-2', teams: Team.create([{name: 'Auburn', team_record: '8-4'}, {name: 'Oklahoma', team_record: '10-2'}]))
Bowl.create(name:'National Championship', points: 36, game_date: '2017-1-9', teams: [Team.find_by(name: 'Alabama'), Team.find_by(name: 'Washington'), Team.find_by(name: 'Clemson'), Team.find_by(name: 'Ohio State')])
