# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rails db:seed command (or created alongside the database with db:setup).
#
# Examples:
#
#   movies = Movie.create([{ name: 'Star Wars' }, { name: 'Lord of the Rings' }])
#   Character.create(name: 'Luke', movie: movies.first)
# Bowl.create(teams: Team.create([{name: 'Kentucky', team_record: '7-5'}, {name: 'Georgia Tech', team_record: '8-4'}]), bowl: Bowl.create(name:'TaxSlayer', points: 10, game_date: '2016-12-31'))

Bowl.create(name:'New Orleans', points: 1, game_date: '2017-12-16', teams: Team.create([{name: 'Troy', team_record: '10-2'}, {name: 'North Texas', team_record: '9-4'}]))
Bowl.create(name:'Cure', points: 1, game_date: '2017-12-16', teams: Team.create([{name: 'WKU', team_record: '6-6'}, {name: 'Georgia State', team_record: '6-5'}]))
Bowl.create(name:'Las Vegas', points: 6, game_date: '2017-12-16', teams: Team.create([{name: 'Boise State', team_record: '10-3'}, {name: 'Oregon', team_record: '7-5'}]))
Bowl.create(name:'New Mexico', points: 2, game_date: '2017-12-16', teams: Team.create([{name: 'Marshall', team_record: '7-5'}, {name: 'Colorado State', team_record: '7-5'}]))
Bowl.create(name:'Camellia', points: 1, game_date: '2017-12-16', teams: Team.create([{name: 'Arkansas State', team_record: '7-4'}, {name: 'Middle Tennessee', team_record: '6-6'}]))
Bowl.create(name:'Boca Raton', points: 1, game_date: '2017-12-19', teams: Team.create([{name: 'Florida Atlantic', team_record: '10-3'}, {name: 'Akron', team_record: '7-6'}]))
Bowl.create(name:'Frisco', points: 1, game_date: '2017-12-20', teams: Team.create([{name: 'Louisiana Tech', team_record: '6-6'}, {name: 'SMU', team_record: '7-5'}]))
Bowl.create(name:'Gasparilla', points: 2, game_date: '2017-12-21', teams: Team.create([{name: 'Temple', team_record: '6-6'}, {name: 'Florida International', team_record: '8-4'}]))
Bowl.create(name:'Bahamas', points: 1, game_date: '2017-12-22', teams: Team.create([{name: 'UAB', team_record: '8-4'}, {name: 'Ohio', team_record: '8-4'}]))
Bowl.create(name:'Famous Idaho Potato', points: 2, game_date: '2017-12-22', teams: Team.create([{name: 'Central Michigan', team_record: '8-4'}, {name: 'Wyoming', team_record: '7-5'}]))
Bowl.create(name:'Birmingham', points: 3, game_date: '2017-12-23', teams: Team.create([{name: 'Texas Tech', team_record: '6-6'}, {name: 'South Florida', team_record: '9-2'}]))
Bowl.create(name:'Armed Forces', points: 3, game_date: '2017-12-23', teams: Team.create([{name: 'Army', team_record: '9-3'}, {name: 'San Diego State', team_record: '10-2'}]))
Bowl.create(name:'Dollar General', points: 2, game_date: '2017-12-23', teams: Team.create([{name: 'Toledo', team_record: '11-2'}, {name: 'Appalachian State', team_record: '8-4'}]))
Bowl.create(name:'Hawaii', points: 2, game_date: '2017-12-24', teams: Team.create([{name: 'Fresno State', team_record: '9-4'}, {name: 'Houston', team_record: '7-4'}]))
Bowl.create(name:'Cactus', points: 3, game_date: '2017-12-26', teams: Team.create([{name: 'Kansas State', team_record: '7-5'}, {name: 'UCLA', team_record: '6-6'}]))
Bowl.create(name:'Quick Lane', points: 3, game_date: '2017-12-26', teams: Team.create([{name: 'Northern Illinois', team_record: '8-4'}, {name: 'Duke', team_record: '6-6'}]))
Bowl.create(name:'Heart of Dallas', points: 3, game_date: '2017-12-26', teams: Team.create([{name: 'West Virginia', team_record: '7-5'}, {name: 'Utah', team_record: '6-6'}]))
Bowl.create(name:'Independence', points: 2, game_date: '2017-12-27', teams: Team.create([{name: 'Florida State', team_record: '6-6'}, {name: 'Southern Miss', team_record: '8-4'}]))
Bowl.create(name:'Pinstripe', points: 6, game_date: '2017-12-27', teams: Team.create([{name: 'Iowa', team_record: '7-5'}, {name: 'Boston College', team_record: '7-5'}]))
Bowl.create(name:'Texas', points: 9, game_date: '2017-12-27', teams: Team.create([{name: 'Texas', team_record: '6-6'}, {name: 'Missouri', team_record: '7-5'}]))
Bowl.create(name:'Foster Farms', points: 6, game_date: '2017-12-27', teams: Team.create([{name: 'Purdue', team_record: '6-6'}, {name: 'Arizona', team_record: '7-5'}]))
Bowl.create(name:'Military', points: 3, game_date: '2017-12-28', teams: Team.create([{name: 'Virginia', team_record: '6-6'}, {name: 'Navy', team_record: '6-6'}]))
Bowl.create(name:'Camping World', points: 9, game_date: '2017-12-28', teams: Team.create([{name: 'Oklahoma State', team_record: '9-3'}, {name: 'Virginia Tech', team_record: '9-3'}]))
Bowl.create(name:'Alamo', points: 9, game_date: '2017-12-28', teams: Team.create([{name: 'Stanford', team_record: '9-4'}, {name: 'TCU', team_record: '10-3'}]))
Bowl.create(name:'Holiday', points: 9, game_date: '2017-12-28', teams: Team.create([{name: 'Michigan State', team_record: '9-3'}, {name: 'Washington State', team_record: '9-3'}]))
Bowl.create(name:'Belk', points: 6, game_date: '2017-12-29', teams: Team.create([{name: 'Wake Forest', team_record: '7-5'}, {name: 'Texas A&M', team_record: '7-5'}]))
Bowl.create(name:'Sun', points: 6, game_date: '2017-12-29', teams: Team.create([{name: 'Arizona State', team_record: '7-5'}, {name: 'NC State', team_record: '8-4'}]))
Bowl.create(name:'Music City', points: 9, game_date: '2017-12-29', teams: Team.create([{name: 'Northwestern', team_record: '9-3'}, {name: 'Kentucky', team_record: '7-5'}]))
Bowl.create(name:'TaxSlayer', points: 6, game_date: '2017-12-30', teams: Team.create([{name: 'Louisville', team_record: '8-4'}, {name: 'Mississippi State', team_record: '8-4'}]))
Bowl.create(name:'Liberty', points: 6, game_date: '2017-12-30', teams: Team.create([{name: 'Iowa State', team_record: '7-5'}, {name: 'Memphis', team_record: '10-2'}]))
Bowl.create(name:'Arizona', points: 1, game_date: '2017-12-30', teams: Team.create([{name: 'New Mexico State', team_record: '6-6'}, {name: 'Utah State', team_record: '6-6'}]))
Bowl.create(name:'Outback', points: 9, game_date: '2018-1-1', teams: Team.create([{name: 'Michigan', team_record: '8-4'}, {name: 'South Carolina', team_record: '8-4'}]))
Bowl.create(name:'Citrus', points: 9, game_date: '2018-1-1', teams: Team.create([{name: 'LSU', team_record: '9-3'}, {name: 'Notre Dame', team_record: '9-3'}]))
Bowl.create(name:'Cotton', points: 12, game_date: '2017-12-29', teams: Team.create([{name: 'USC', team_record: '11-2'}, {name: 'Ohio State', team_record: '11-2'}]))
Bowl.create(name:'Fiesta', points: 12, game_date: '2017-12-30', teams: Team.create([{name: 'Washington', team_record: '10-2'}, {name: 'Penn State', team_record: '10-2'}]))
Bowl.create(name:'Orange', points: 12, game_date: '2017-12-30', teams: Team.create([{name: 'Miami', team_record: '10-2'}, {name: 'Wisconsin', team_record: '12-1'}]))
Bowl.create(name:'Peach', points: 12, game_date: '2018-1-1', teams: Team.create([{name: 'UCF', team_record: '12-0'}, {name: 'Auburn', team_record: '10-3'}]))
Bowl.create(name:'Rose', points: 12, game_date: '2018-1-1', teams: Team.create([{name: 'Georgia', team_record: '12-1'}, {name: 'Oklahoma', team_record: '12-1'}]))
Bowl.create(name:'Sugar', points: 12, game_date: '2018-1-1', teams: Team.create([{name: 'Alabama', team_record: '11-1'}, {name: 'Clemson', team_record: '12-1'}]))
Bowl.create(name:'National Championship', points: 12, game_date: '2017-1-8', teams: [Team.find_by(name: 'Clemson'), Team.find_by(name: 'Oklahoma'), Team.find_by(name: 'Georgia'), Team.find_by(name: 'Alabama')])
